remote_theme: just-the-docs/just-the-docs
name: Mingzhe Hu
title: null
url: "https://superbtum.github.io"
title-heading: false

logo: "https://superbtum.github.io/images/columbia_logo_1.png"

markdown: Kramdown
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
]


defaults:
  - scope: 
      path: ""
      type: pages
    values: 
      author_profile: true

author:
  name: "Mingzhe Hu"
  avatar: "/images/humingzhe.jpg"
  bio: "Columbia x Nvidia" # Note: Markdown is allowed
  location: "New York City"

# Navigation disabled for single-page layout

# Search disabled for single-page layout
search_enabled: false

# Enable or disable heading anchors
heading_anchors: true


# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Mingzhe Hu. Distributed by an <a href=\"https://github.com/SuperbTUM/superbTUM.github.io/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-HZGS61TX68
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
