theme: jekyll-theme-cayman
title: MingzheHu's homepage
description: master student at Columbia
url: "https://superbtum.github.io"
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

avatar: "/images/campus_morningside.jpg"
# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true
