theme: jekyll-theme-cayman
title: Mingzhe Hu
description: master student at Columbia
url: "https://superbtum.github.io"
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


social-network-links:
  email: "mingzhe.hu@columbia.edu"
  github: SuperbTUM


